everthing else..

diff --git a/shell/wali b/shell/wali
--- a/shell/wali
+++ b/shell/wali
@@ -1,12 +1,25 @@
 #
 # wallpaper switcher
 # wraps pywal + chooses a random image from a specified dir
+# supports both X11 (feh) and Wayland/Hyprland (swww)
 # https://github.com/khughitt/wali
+#
 
 # skip for ubuntu hosts
 if [ -f /etc/lsb-release ] && grep -q Ubuntu /etc/lsb-release; then
   return
 fi
+
+# detect display server
+if [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
+  WALI_BACKEND="swww"
+else
+  WALI_BACKEND="feh"
+fi
+
+# output format for wali_ingest (jpg or png)
+# set WALI_FORMAT before sourcing this file to override
+: "${WALI_FORMAT:=jpg}"
 
 # kitty image previews
 # https://github.com/junegunn/fzf/issues/3228#issuecomment-1730781875
@@ -16,85 +29,113 @@ KITTY_PREVIEW_CMD='kitten icat \
     --stdin=no \
     --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@20x1 {}\
     > /dev/tty'
-  
+
 # wallpaper switcher
-alias wali="cd ~/d/wali/ && poetry run wali --image-dir=\"$WALI_DIR/3440\" change"
+if [ "$WALI_BACKEND" = "swww" ]; then
+  alias wali="cd ~/d/wali/ && uv run wali --image-dir=\"\$WALI_DIR/3440\" --wallpaper-backend swww change"
+else
+  alias wali="cd ~/d/wali/ && uv run wali --image-dir=\"\$WALI_DIR/3440\" change"
+fi
 
-# print path to original version of image used in current background
-function wali_print {
-  file=$(/bin/cat ~/.fehbg | grep -Eo --color='never' "[\/a-z0-9]+PXL.*.png")
-  datestr=`echo $file | cut -d '_' -f2`
+# apply pywal colors and set wallpaper (swww only)
+function wali_set {
+  local img="$1"
 
-  year=`date -d $datestr +%Y`
-  mon=`date -d $datestr +%m`
-
-  # file=${file/3440/orig\/$year\/$mon}
-  # /home/keith/d/linux/backgrounds/3440/PXL_20240520_023703962.png
-  #file=${file/3440/orig\/$year\/$mon}
-  root_dir="$BACKGROUND_IMG_DIR"
-  file=`basename $file`
-
-  echo "$root_dir/$year/$mon/${file/png/jpg}"
-}
-
-# open the current original version of the current background in gimp
-alias wali_edit_current='gimp `wali_print`'
-
-#
-# search for an image by name and add it to the "favorites" list
-# 
-function wali_search {
-  target=`fd $1 $WALI_DIR/3440 |\
-    grep --color='none' "$1" |\
-    fzf -1 --exact --preview=$KITTY_PREVIEW_CMD`
-
-  [ ! -z "$target" ] && echo "Adding $target to favorites.." && echo $target >> "$WALI_DIR/favorites.txt"
-}
-
-#
-# add the current background to the "favorites" list
-alias wali_save='wali_print >> $WALI_DIR/favorites.txt'
-
-# select an image from the favorites list and open it in gimp
-function wali_edit_fav { 
-  target=`/bin/cat $WALI_DIR/favorites.txt |\
-    grep --color='none' "$1" |\
-    fzf -1 --exact --preview=$KITTY_PREVIEW_CMD`
-
-  # determine which prefix to use
-  # /mnt/ssd2/backgrounds/2024/05/PXL_20240526_175819114.jpg
-  # /home/keith/d/linux/backgrounds/orig/2022/10/PXL_20221023_211629715.jpg
-
-  # get the directory of the image
-  imgdir=`dirname "$target"`
-
-  # get the year and month of the image
-
-  # get the year and month of the image
-  year=`echo $imgdir | cut -d '/' -f 5`
-  mon=`echo $imgdir | cut -d '/' -f 6`
-
-  # get the prefix
-  prefix="/home/keith/d/linux/backgrounds/orig/$year/$mon"
-  
-  # che
-  if [ ! -e "$target" ]; then
-    # check alt path
-    if [ -e "$prefix/$target" ]; then
-      target="$prefix/$target" 
-    fi
+  if [ -z "$img" ]; then
+    echo "Usage: wali_set <image-path>"
+    return 1
   fi
 
-  [ ! -z "$target" ] && /bin/gimp $target
+  # generate colors with pywal
+  wal -i "$img" -n
+
+  if [ "$WALI_BACKEND" = "swww" ]; then
+    swww img "$img" \
+      --transition-type wipe \
+      --transition-duration 2 \
+      --transition-fps 60
+  else
+    feh --bg-fill "$img"
+  fi
+}
+
+# print path to original source image for current wallpaper
+function wali_print {
+  local file
+
+  # get current wallpaper path
+  if [ "$WALI_BACKEND" = "swww" ]; then
+    file=$(swww query | grep -oP 'image: \K.*' | head -n1)
+  else
+    file=$(/bin/cat ~/.fehbg | /bin/grep -Eo "[\/a-z0-9]+PXL.*\.(jpg|png)")
+  fi
+
+  # extract filename and parse date (PXL_20240520_023703962.jpg -> 20240520)
+  local fname=$(basename "$file")
+  local datestr=$(echo "$fname" | cut -d '_' -f2)
+  local year=$(date -d "$datestr" +%Y)
+  local mon=$(date -d "$datestr" +%m)
+
+  # construct path to original source image
+  echo "$BACKGROUND_IMG_DIR/$year/$mon/${fname%.*}.jpg"
+}
+
+# open the current wallpaper in gimp
+alias wali_edit_current='gimp "$(wali_print)"'
+
+# search for an image by name and add it to the "favorites" list
+function wali_search {
+  target=$(fd "$1" "$WALI_DIR/3440" | \
+    grep --color='none' "$1" | \
+    fzf -1 --exact --preview=$KITTY_PREVIEW_CMD)
+
+  [ ! -z "$target" ] && echo "Adding $target to favorites.." && echo "$target" >> "$WALI_DIR/favorites.txt"
+}
+
+# add the current background to the "favorites" list
+function wali_save {
+  local current=$(wali_print)
+  echo "$current" >> "$WALI_DIR/favorites.txt"
+  echo "Saved: $current"
+}
+
+# select an image from the favorites list and open it in gimp
+function wali_edit_fav {
+  # "tac" = reverse "cat" (lines in reverse order)
+  target=$(/bin/tac "$WALI_DIR/favorites.txt" | \
+    grep --color='none' "$1" | \
+    fzf -1 --exact --preview=$KITTY_PREVIEW_CMD)
+
+  if [ -z "$target" ]; then
+    return
+  fi
+
+  # if target exists directly, use it
+  if [ -e "$target" ]; then
+    /bin/gimp "$target"
+    return
+  fi
+
+  # try to resolve path from favorites entry (X11 legacy format)
+  local imgdir=$(dirname "$target")
+  local year=$(echo "$imgdir" | cut -d '/' -f 5)
+  local mon=$(echo "$imgdir" | cut -d '/' -f 6)
+  local prefix="/home/keith/d/linux/backgrounds/orig/$year/$mon"
+
+  if [ -e "$prefix/$target" ]; then
+    /bin/gimp "$prefix/$target"
+  else
+    echo "File not found: $target"
+  fi
 }
 
 # find an image by name and open it in gimp
 function wali_edit_search {
-  target=`fd $1 $WALI_DIR/3440 |\
-    grep --color='none' "$1" |\
-    fzf -1 --exact --preview=$KITTY_PREVIEW_CMD`
+  target=$(fd "$1" "$WALI_DIR/3440" | \
+    grep --color='none' "$1" | \
+    fzf -1 --exact --preview=$KITTY_PREVIEW_CMD)
 
-  [ ! -z "$target" ] && echo "opening $target.." && /bin/gimp $target
+  [ ! -z "$target" ] && echo "Opening $target.." && /bin/gimp "$target"
 }
 
 # create png palette based on wal colors
@@ -106,39 +147,120 @@ function wali_pal {
   magick -append /tmp/a.png /tmp/b.png ~/.cache/wal/palette.png
 }
 
+# reload pywal colors in running applications
+function wali_reload {
+  if [ "$WALI_BACKEND" = "swww" ]; then
+    # reload waybar with new colors
+    killall waybar 2>/dev/null
+    ~/.config/waybar/launch.sh &
+  fi
+
+  # reload kitty colors
+  killall -SIGUSR1 kitty 2>/dev/null
+
+  echo "Reloaded pywal colors"
+}
+
+# process a single image into 3440px-wide wallpaper
+# usage: _wali_process_image <source> <outfile> <mode>
+# modes: landscape (resize only), rotate (rotate 90° + resize), crop (center-crop 21:9 + resize)
+function _wali_process_image {
+  local src="$1" outfile="$2" mode="$3"
+
+  local dims=$(identify "$src" | cut -d ' ' -f 3)
+  local w=$(echo "$dims" | cut -d 'x' -f 1)
+  local h=$(echo "$dims" | cut -d 'x' -f 2)
+
+  local cmd="magick $src"
+
+  case "$mode" in
+    rotate)
+      cmd="$cmd -rotate 90"
+      ;;
+    crop)
+      local crop_h=$((w * 9 / 21))
+      cmd="$cmd -gravity center -crop ${w}x${crop_h}+0+0 +repage"
+      ;;
+  esac
+
+  cmd="$cmd -resize 3440x"
+  if [ "$WALI_FORMAT" = "jpg" ]; then
+    cmd="$cmd -quality 90"
+  fi
+  cmd="$cmd $outfile"
+
+  echo "$cmd"
+  eval "$cmd"
+
+  if [ "$WALI_FORMAT" = "jpg" ]; then
+    jpegoptim --strip-none "$outfile"
+  else
+    oxipng -o 4 "$outfile"
+  fi
+}
+
 # image ingestion
 function wali_ingest {
   for x in $BACKGROUND_IMG_DIR/*/*/*.jpg; do
-    # output filepath
-    fname=${x##*/}
-    outfile="$WALI_DIR/3440/${fname/.jpg/.png}"
+    local fname=${x##*/}
+    local outfile="$WALI_DIR/3440/${fname%.jpg}.$WALI_FORMAT"
 
     if [ ! -e "$outfile" ]; then
-      # initial convert command
-      cmd="magick $x"
+      local dims=$(identify "$x" | cut -d ' ' -f 3)
+      local w=$(echo "$dims" | cut -d 'x' -f 1)
+      local h=$(echo "$dims" | cut -d 'x' -f 2)
 
-      # get width/height
-      dims=`identify $x | cut -d ' ' -f 3`
-
-      w=`echo $dims | cut -d 'x' -f 1`
-      h=`echo $dims | cut -d 'x' -f 2`
-
-      # if height > width, rotate image
       if [ "$h" -gt "$w" ]; then
-        cmd="$cmd -rotate 90"
+        kitten icat --clear --transfer-mode=memory --stdin=no "$x"
+        echo "\n$(basename "$x") (${w}x${h})"
+        echo -n "[r]otate / [c]rop / [s]kip? "
+        read -r choice
+        case "$choice" in
+          r) _wali_process_image "$x" "$outfile" rotate ;;
+          c) _wali_process_image "$x" "$outfile" crop ;;
+          *) echo "Skipping $fname"; continue ;;
+        esac
+      else
+        _wali_process_image "$x" "$outfile" landscape
       fi
-
-      cmd="$cmd -resize 3440x $outfile"
-
-      echo $cmd
-      eval $cmd
-
-      # strip metadata
-      mogrify -strip $outfile
-
-      # squish
-      oxipng -o 4 $outfile
     fi
+  done
+}
+
+# reprocess portrait images that already have processed versions
+function wali_reprocess {
+  local src_path="${1:?Usage: wali_reprocess <source_path>}"
+
+  if [ ! -d "$src_path" ]; then
+    echo "Directory not found: $src_path"
+    return 1
+  fi
+
+  for x in "$src_path"/**/*.jpg; do
+    [ -f "$x" ] || continue
+
+    local fname=${x##*/}
+    local outfile="$WALI_DIR/3440/${fname%.jpg}.$WALI_FORMAT"
+
+    # only reprocess files that already have a processed version
+    [ -e "$outfile" ] || continue
+
+    local dims=$(identify "$x" | cut -d ' ' -f 3)
+    local w=$(echo "$dims" | cut -d 'x' -f 1)
+    local h=$(echo "$dims" | cut -d 'x' -f 2)
+
+    # only prompt for portrait images
+    [ "$h" -gt "$w" ] || continue
+
+    kitten icat --clear --transfer-mode=memory --stdin=no "$x"
+    echo "\n$(basename "$x") (${w}x${h})"
+    echo -n "[r]otate / [c]rop / [s]kip? "
+    read -r choice
+    case "$choice" in
+      r) rm "$outfile"; _wali_process_image "$x" "$outfile" rotate ;;
+      c) rm "$outfile"; _wali_process_image "$x" "$outfile" crop ;;
+      *) echo "Skipping $fname" ;;
+    esac
   done
 }
 
